name: Push Web Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Instala Emacs y ejecuta publish.el
        run: |
          sudo apt-get update
          sudo apt-get install emacs -y
	  emacs --batch --eval "(require 'package)" \
          	--eval "(add-to-list 'package-archives '(\"melpa\" . \"https://melpa.org/packages/\"))" \
          	--eval "(package-initialize)" \
          	--eval "(package-refresh-contents)" \
          	--eval "(package-install 'htmlize)"
          emacs --batch -l publish.el
          pwd
          ls
          ls docs/*

      - name: Deploy docs/ a gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          destination_dir: docs